BEGIN
    FOR U IN (SELECT USERNAME FROM DBA_USERS WHERE DEFAULT_TABLESPACE = 'TS_PLYTIX') LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || U.USERNAME || 'CASCADE';
    END LOOP;
    FOR T IN (SELECT TABLE_NAME FROM DBA_TABLES WHERE OWNER = 'PLYTIX') LOOP
        EXECUTE IMMEDIATE 'DROP TABLE PLYTIX.' || T.TABLE_NAME || 'CASCADE CONSTRAINTS';
    END LOOP;
    FOR V IN (SELECT VIEW_NAME FROM DBA_VIEWS WHERE OWNER = 'PLYTIX') LOOP
        EXECUTE IMMEDIATE 'DROP VIEW PLYTIX.' || V.VIEW_NAME;
    END LOOP;
    FOR S IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = 'PLYTIX_MP') LOOP
        EXECUTE IMMEDIATE 'DROP SYNONYM PLYTIX_MP.' || S.SYNONYM_NAME || '';
    END LOOP;

    DROP TABLESPACE TS_INDICES INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
    DROP TABLESPACE TS_PLYTIX INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

END;
/