
drop user PLYTIX cascade;

BEGIN
    FOR T IN (SELECT TABLE_NAME FROM DBA_TABLES WHERE OWNER = 'PLYTIX') LOOP
        EXECUTE IMMEDIATE 'DROP TABLE PLYTIX.' || T.TABLE_NAME || 'CASCADE CONSTRAINTS';
    END LOOP;
    FOR V IN (SELECT VIEW_NAME FROM DBA_VIEWS WHERE OWNER = 'PLYTIX') LOOP
        EXECUTE IMMEDIATE 'DROP VIEW PLYTIX.' || V.VIEW_NAME;
    END LOOP;
    FOR S IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = 'PLYTIX_MP') LOOP
        EXECUTE IMMEDIATE 'DROP SYNONYM PLYTIX_MP.' || S.SYNONYM_NAME || '';
    END LOOP;
END;
/